const UsersSchema = {
  table: "users",

  columns: {
    id: {
      type: "bigint",
      primary: true,
      autoGenerated: true,
    },

    created_at: {
      type: "timestamp",
      default: "now()",
    },

    name: {
      type: "varchar",
      length: 255,
    },

    email: {
      type: "varchar",
      length: 255,
    },
  },
};

export default UsersSchema;
