-- MASSIVE SEED DATA for ISS Project
-- This creates an extremely rich database with hundreds of records

-- =====================================================
-- ADD 100+ SKILLS (All Categories)
-- =====================================================
INSERT INTO skills (name, category) VALUES
    -- Programming Languages (30+)
    ('C++', 'Programming Language'),
    ('Scala', 'Programming Language'),
    ('R', 'Programming Language'),
    ('MATLAB', 'Programming Language'),
    ('Perl', 'Programming Language'),
    ('Haskell', 'Programming Language'),
    ('Elixir', 'Programming Language'),
    ('Clojure', 'Programming Language'),
    ('Dart', 'Programming Language'),
    ('Objective-C', 'Programming Language'),
    ('F#', 'Programming Language'),
    ('Lua', 'Programming Language'),
    ('Julia', 'Programming Language'),
    ('VB.NET', 'Programming Language'),
    ('Assembly', 'Programming Language'),
    ('Shell Scripting', 'Programming Language'),
    ('PowerShell', 'Programming Language'),
    ('Solidity', 'Programming Language'),
    
    -- Frontend Frameworks & Libraries (20+)
    ('Remix', 'Frontend Framework'),
    ('Astro', 'Frontend Framework'),
    ('Solid.js', 'Frontend Framework'),
    ('Preact', 'Frontend Framework'),
    ('Alpine.js', 'Frontend Framework'),
    ('Backbone.js', 'Frontend Framework'),
    ('Ember.js', 'Frontend Framework'),
    ('Polymer', 'Frontend Framework'),
    ('Lit', 'Frontend Framework'),
    ('Qwik', 'Frontend Framework'),
    ('Material-UI', 'UI Library'),
    ('Ant Design', 'UI Library'),
    ('Chakra UI', 'UI Library'),
    ('Shadcn/ui', 'UI Library'),
    ('Vuetify', 'UI Library'),
    ('PrimeReact', 'UI Library'),
    ('React Native', 'Mobile Framework'),
    ('Flutter', 'Mobile Framework'),
    ('Ionic', 'Mobile Framework'),
    ('NativeScript', 'Mobile Framework'),
    
    -- Backend Frameworks (20+)
    ('Express.js', 'Backend Framework'),
    ('NestJS', 'Backend Framework'),
    ('Koa', 'Backend Framework'),
    ('Hapi', 'Backend Framework'),
    ('Fastify', 'Backend Framework'),
    ('Laravel', 'Backend Framework'),
    ('Symphony', 'Backend Framework'),
    ('Ruby on Rails', 'Backend Framework'),
    ('Sinatra', 'Backend Framework'),
    ('ASP.NET Core', 'Backend Framework'),
    ('Gin', 'Backend Framework'),
    ('Echo', 'Backend Framework'),
    ('Fiber', 'Backend Framework'),
    ('Actix', 'Backend Framework'),
    ('Rocket', 'Backend Framework'),
    ('Phoenix', 'Backend Framework'),
    ('Vapor', 'Backend Framework'),
    ('Ktor', 'Backend Framework'),
    ('Micronaut', 'Backend Framework'),
    ('Quarkus', 'Backend Framework'),
    
    -- Databases (25+)
    ('Supabase', 'Database'),
    ('Firebase', 'Database'),
    ('CouchDB', 'Database'),
    ('Neo4j', 'Database'),
    ('ArangoDB', 'Database'),
    ('InfluxDB', 'Database'),
    ('TimescaleDB', 'Database'),
    ('Elasticsearch', 'Database'),
    ('Solr', 'Database'),
    ('Memcached', 'Database'),
    ('SQLite', 'Database'),
    ('MariaDB', 'Database'),
    ('RethinkDB', 'Database'),
    ('ScyllaDB', 'Database'),
    ('CockroachDB', 'Database'),
    ('PlanetScale', 'Database'),
    ('FaunaDB', 'Database'),
    ('EdgeDB', 'Database'),
    ('SurrealDB', 'Database'),
    ('ClickHouse', 'Database'),
    ('Snowflake', 'Database'),
    ('BigQuery', 'Database'),
    ('Redshift', 'Database'),
    ('Databricks', 'Database'),
    
    -- DevOps & Cloud (30+)
    ('CircleCI', 'CI/CD'),
    ('Travis CI', 'CI/CD'),
    ('Bamboo', 'CI/CD'),
    ('TeamCity', 'CI/CD'),
    ('Azure DevOps', 'CI/CD'),
    ('Argo CD', 'CI/CD'),
    ('Flux', 'CI/CD'),
    ('Spinnaker', 'CI/CD'),
    ('Helm', 'DevOps'),
    ('Istio', 'DevOps'),
    ('Linkerd', 'DevOps'),
    ('Consul', 'DevOps'),
    ('Nomad', 'DevOps'),
    ('Vault', 'DevOps'),
    ('Pulumi', 'Infrastructure as Code'),
    ('CloudFormation', 'Infrastructure as Code'),
    ('CDK', 'Infrastructure as Code'),
    ('Vagrant', 'DevOps'),
    ('Packer', 'DevOps'),
    ('VMware', 'Virtualization'),
    ('OpenStack', 'Cloud Platform'),
    ('DigitalOcean', 'Cloud Platform'),
    ('Linode', 'Cloud Platform'),
    ('Heroku', 'Cloud Platform'),
    ('Vercel', 'Cloud Platform'),
    ('Netlify', 'Cloud Platform'),
    ('Cloudflare', 'Cloud Platform'),
    ('Fastly', 'CDN'),
    ('Akamai', 'CDN'),
    ('New Relic', 'Monitoring'),
    ('Datadog', 'Monitoring'),
    ('Splunk', 'Monitoring'),
    ('AppDynamics', 'Monitoring'),
    ('Dynatrace', 'Monitoring'),
    ('PagerDuty', 'Incident Management'),
    
    -- AI/ML & Data Science (30+)
    ('Keras', 'AI/ML'),
    ('Hugging Face', 'AI/ML'),
    ('LangChain', 'AI/ML'),
    ('OpenAI API', 'AI/ML'),
    ('Anthropic Claude', 'AI/ML'),
    ('Stable Diffusion', 'AI/ML'),
    ('DALL-E', 'AI/ML'),
    ('Midjourney', 'AI/ML'),
    ('OpenCV', 'Computer Vision'),
    ('YOLO', 'Computer Vision'),
    ('spaCy', 'Natural Language Processing'),
    ('NLTK', 'Natural Language Processing'),
    ('Transformers', 'AI/ML'),
    ('BERT', 'Natural Language Processing'),
    ('GPT', 'Natural Language Processing'),
    ('XGBoost', 'AI/ML'),
    ('LightGBM', 'AI/ML'),
    ('CatBoost', 'AI/ML'),
    ('MLflow', 'MLOps'),
    ('Kubeflow', 'MLOps'),
    ('Weights & Biases', 'MLOps'),
    ('DVC', 'MLOps'),
    ('Apache Spark', 'Big Data'),
    ('Hadoop', 'Big Data'),
    ('Flink', 'Big Data'),
    ('Airflow', 'Data Orchestration'),
    ('Dagster', 'Data Orchestration'),
    ('Prefect', 'Data Orchestration'),
    ('dbt', 'Data Transformation'),
    ('Pandas', 'Data Analysis'),
    ('NumPy', 'Data Analysis'),
    ('Jupyter', 'Data Analysis'),
    ('Tableau', 'Data Visualization'),
    ('Power BI', 'Data Visualization'),
    ('Looker', 'Data Visualization'),
    ('Metabase', 'Data Visualization'),
    ('Superset', 'Data Visualization'),
    
    -- Testing & Quality (15+)
    ('Playwright', 'Testing'),
    ('Puppeteer', 'Testing'),
    ('TestCafe', 'Testing'),
    ('Mocha', 'Testing'),
    ('Jasmine', 'Testing'),
    ('Karma', 'Testing'),
    ('PyTest', 'Testing'),
    ('unittest', 'Testing'),
    ('JUnit', 'Testing'),
    ('Cucumber', 'Testing'),
    ('Postman', 'API Testing'),
    ('Insomnia', 'API Testing'),
    ('SonarQube', 'Code Quality'),
    ('ESLint', 'Code Quality'),
    ('Prettier', 'Code Quality'),
    
    -- Security (15+)
    ('OWASP', 'Security'),
    ('Snyk', 'Security'),
    ('Burp Suite', 'Security'),
    ('Metasploit', 'Security'),
    ('Wireshark', 'Security'),
    ('Nmap', 'Security'),
    ('OAuth', 'Security'),
    ('JWT', 'Security'),
    ('Auth0', 'Security'),
    ('Keycloak', 'Security'),
    ('SSL/TLS', 'Security'),
    ('Penetration Testing', 'Security'),
    ('Security Auditing', 'Security'),
    ('GDPR Compliance', 'Security'),
    ('SOC 2', 'Security'),
    
    -- Web Technologies (15+)
    ('WebSockets', 'Web Development'),
    ('WebRTC', 'Web Development'),
    ('Service Workers', 'Web Development'),
    ('IndexedDB', 'Web Development'),
    ('Web Components', 'Web Development'),
    ('WebGL', 'Web Development'),
    ('Three.js', '3D Graphics'),
    ('D3.js', 'Data Visualization'),
    ('Chart.js', 'Data Visualization'),
    ('Recharts', 'Data Visualization'),
    ('Leaflet', 'Mapping'),
    ('Mapbox', 'Mapping'),
    ('Google Maps API', 'Mapping'),
    ('SEO', 'Web Development'),
    ('Web Accessibility', 'Web Development'),
    
    -- Misc Modern Tech (20+)
    ('Blockchain', 'Emerging Tech'),
    ('Web3', 'Emerging Tech'),
    ('Smart Contracts', 'Emerging Tech'),
    ('NFT Development', 'Emerging Tech'),
    ('Ethereum', 'Blockchain'),
    ('Polygon', 'Blockchain'),
    ('IoT', 'Emerging Tech'),
    ('Raspberry Pi', 'Hardware'),
    ('Arduino', 'Hardware'),
    ('5G Technology', 'Networking'),
    ('Edge Computing', 'Cloud Computing'),
    ('Quantum Computing', 'Emerging Tech'),
    ('AR/VR', 'Extended Reality'),
    ('Unity', 'Game Development'),
    ('Unreal Engine', 'Game Development'),
    ('Godot', 'Game Development'),
    ('Game Design', 'Game Development'),
    ('Technical Writing', 'Soft Skills'),
    ('System Design', 'Software Architecture'),
    ('Design Patterns', 'Software Architecture')
ON CONFLICT (name) DO NOTHING;

-- =====================================================
-- ADD 50+ TRENDS
-- =====================================================
INSERT INTO trends (domain, title, description, source) VALUES
    -- AI & Automation
    ('AI/ML', 'AI Agents and Autonomous Systems', 'Development of AI agents that can perform complex tasks autonomously', 'Anthropic'),
    ('AI/ML', 'Multimodal AI', 'AI systems that can process multiple types of data (text, image, audio)', 'Google DeepMind'),
    ('AI/ML', 'AI Code Generation', 'Tools that generate production-ready code from natural language', 'GitHub'),
    ('AI/ML', 'Retrieval Augmented Generation (RAG)', 'Enhancing LLMs with external knowledge bases', 'OpenAI'),
    ('AI/ML', 'Fine-tuning Open Source Models', 'Customizing open-source LLMs for specific use cases', 'Hugging Face'),
    ('AI/ML', 'AI Observability', 'Monitoring and debugging AI systems in production', 'Arize AI'),
    ('AI/ML', 'Federated Learning', 'Training ML models across decentralized data sources', 'Google'),
    ('AI/ML', 'Explainable AI', 'Making AI decisions transparent and interpretable', 'DARPA'),
    ('AI/ML', 'AI Ethics and Governance', 'Establishing guidelines for responsible AI development', 'Partnership on AI'),
    ('AI/ML', 'Edge AI', 'Running AI models directly on edge devices', 'NVIDIA'),
    
    -- Cloud & Infrastructure
    ('Cloud Computing', 'Serverless Containers', 'Container-based serverless computing platforms', 'Google Cloud Run'),
    ('Cloud Computing', 'Kubernetes Everywhere', 'Universal adoption of K8s for container orchestration', 'CNCF'),
    ('Cloud Computing', 'Cloud Cost Optimization', 'Tools and practices for managing cloud expenses', 'FinOps Foundation'),
    ('Cloud Computing', 'Green Cloud Computing', 'Sustainable and energy-efficient cloud practices', 'Green Software Foundation'),
    ('Cloud Computing', 'Cloud-Native Development', 'Building applications specifically for cloud environments', 'CNCF'),
    ('Cloud Computing', 'Multi-Cloud Management', 'Tools for managing resources across cloud providers', 'HashiCorp'),
    ('Cloud Computing', 'Infrastructure Automation', 'Complete automation of infrastructure provisioning', 'Terraform'),
    
    -- Development Practices
    ('Software Development', 'Shift-Left Testing', 'Moving testing earlier in the development cycle', 'DevOps Institute'),
    ('Software Development', 'Continuous Deployment', 'Automated deployment pipelines to production', 'GitLab'),
    ('Software Development', 'Feature Flags', 'Dynamic feature toggling in production', 'LaunchDarkly'),
    ('Software Development', 'Trunk-Based Development', 'Simplified branching strategy for faster releases', 'ThoughtWorks'),
    ('Software Development', 'Domain-Driven Design', 'Aligning code structure with business domains', 'Eric Evans'),
    ('Software Development', 'CQRS and Event Sourcing', 'Separating read and write operations', 'Greg Young'),
    ('Software Development', 'Functional Programming', 'Increased adoption of FP principles', 'Functional Works'),
    ('Software Development', 'Type Safety', 'Stronger type systems in dynamic languages', 'TypeScript'),
    ('Software Development', 'Developer Experience (DX)', 'Optimizing tools and workflows for developers', 'Netlify'),
    
    -- Web Development
    ('Web Development', 'Server Components', 'Rendering React components on the server', 'React'),
    ('Web Development', 'Islands Architecture', 'Selective hydration for better performance', 'Astro'),
    ('Web Development', 'Web Vitals', 'Focus on core web performance metrics', 'Google'),
    ('Web Development', 'Micro Frontends', 'Breaking frontends into smaller, independent pieces', 'ThoughtWorks'),
    ('Web Development', 'Headless CMS', 'Content management systems with API-first approach', 'Contentful'),
    ('Web Development', 'Static Site Generation', 'Pre-rendering pages at build time', 'Next.js'),
    ('Web Development', 'Incremental Static Regeneration', 'Hybrid approach between SSG and SSR', 'Vercel'),
    ('Web Development', 'Progressive Enhancement', 'Building resilient web experiences', 'MDN'),
    
    -- Data & Analytics
    ('Data Engineering', 'Real-Time Analytics', 'Processing and analyzing streaming data', 'Confluent'),
    ('Data Engineering', 'Data Lakehouse', 'Combining data lakes and warehouses', 'Databricks'),
    ('Data Engineering', 'Reverse ETL', 'Moving data from warehouses back to operational tools', 'Hightouch'),
    ('Data Engineering', 'Data Observability', 'Monitoring data pipelines for quality and reliability', 'Monte Carlo'),
    ('Data Engineering', 'Modern Data Stack', 'Cloud-based tools for data engineering', 'dbt Labs'),
    ('Data Science', 'Causal Inference', 'Understanding cause-and-effect relationships in data', 'Microsoft Research'),
    ('Data Science', 'Synthetic Data Generation', 'Creating artificial data for testing and training', 'Google'),
    
    -- Security & Privacy
    ('Security', 'Zero Trust Network Access', 'Network security based on verification', 'NIST'),
    ('Security', 'Supply Chain Security', 'Securing software dependencies and build process', 'OWASP'),
    ('Security', 'Container Security', 'Securing containerized applications', 'Aqua Security'),
    ('Security', 'Policy as Code', 'Defining security policies in code', 'Open Policy Agent'),
    ('Security', 'Privacy-Enhancing Technologies', 'Technologies that protect user privacy', 'W3C'),
    ('Security', 'Quantum-Safe Cryptography', 'Preparing for quantum computing threats', 'NIST'),
    
    -- Emerging Technologies
    ('Emerging Tech', 'WebAssembly Beyond Browsers', 'Using WASM for server-side applications', 'Bytecode Alliance'),
    ('Emerging Tech', 'Decentralized Applications (dApps)', 'Building apps on blockchain networks', 'Ethereum Foundation'),
    ('Emerging Tech', 'Metaverse Development', 'Creating immersive virtual experiences', 'Meta'),
    ('Emerging Tech', 'Digital Twins', 'Virtual replicas of physical systems', 'Azure'),
    ('Emerging Tech', 'Ambient Computing', 'Computing integrated into environment', 'Google'),
    ('Emerging Tech', 'Neuromorphic Computing', 'Brain-inspired computer architectures', 'Intel');

-- =====================================================
-- ADD 50+ USERS WITH DIVERSE BACKGROUNDS
-- =====================================================
INSERT INTO users (email, password_hash, full_name) VALUES
    -- Tech professionals
    ('alex.chen@tech.com', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Alex Chen'),
    ('priya.sharma@dev.io', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Priya Sharma'),
    ('marcus.williams@cloud.com', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Marcus Williams'),
    ('yuki.tanaka@ml.ai', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Yuki Tanaka'),
    ('sofia.rodriguez@startup.io', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Sofia Rodriguez'),
    ('liam.otoole@enterprise.com', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Liam O''Toole'),
    ('fatima.hassan@security.net', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Fatima Hassan'),
    ('kai.mueller@devops.de', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Kai Mueller'),
    ('isabella.santos@data.br', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Isabella Santos'),
    ('henrik.larsen@mobile.dk', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Henrik Larsen'),
    ('amara.okafor@fintech.ng', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Amara Okafor'),
    ('jin.park@gaming.kr', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Jin Park'),
    ('elena.popov@backend.ru', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Elena Popov'),
    ('omar.khalil@blockchain.ae', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Omar Khalil'),
    ('maya.cohen@frontend.il', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Maya Cohen'),
    ('thabo.ndlovu@iot.za', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Thabo Ndlovu'),
    ('clara.moreau@ai.fr', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Clara Moreau'),
    ('ravi.patel@saas.in', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Ravi Patel'),
    ('nadia.volkov@quantum.ru', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Nadia Volkov'),
    ('diego.fernandez@ecommerce.mx', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Diego Fernandez'),
    ('aisha.rahman@analytics.bd', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Aisha Rahman'),
    ('lucas.bergstrom@ux.se', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Lucas Bergstrom'),
    ('zara.ali@platform.pk', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Zara Ali'),
    ('oliver.schmidt@automotive.de', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Oliver Schmidt'),
    ('leila.mansouri@robotics.ir', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Leila Mansouri'),
    ('santiago.lopez@gaming.ar', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Santiago Lopez'),
    ('mei.wong@design.hk', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Mei Wong'),
    ('andre.silva@api.pt', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Andre Silva'),
    ('ingrid.hansen@mobile.no', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Ingrid Hansen'),
    ('kwame.mensah@web3.gh', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Kwame Mensah'),
    ('natasha.ivanova@systems.ua', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Natasha Ivanova'),
    ('jamal.osman@infrastructure.so', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Jamal Osman'),
    ('catalina.gomez@microservices.co', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Catalina Gomez'),
    ('ibrahim.yilmaz@database.tr', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Ibrahim Yilmaz'),
    ('anastasia.petrova@nlp.by', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Anastasia Petrova'),
    ('takumi.sato@architecture.jp', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Takumi Sato'),
    ('jasmine.nguyen@testing.vn', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Jasmine Nguyen'),
    ('mohamed.el-sayed@embedded.eg', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Mohamed El-Sayed'),
    ('freya.andersen@performance.dk', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Freya Andersen'),
    ('raj.kumar@distributed.in', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Raj Kumar'),
    ('valentina.rossi@product.it', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Valentina Rossi'),
    ('arjun.mehta@streaming.in', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Arjun Mehta'),
    ('sofia.kowalski@integration.pl', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Sofia Kowalski'),
    ('kenji.yamamoto@vr.jp', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Kenji Yamamoto'),
    ('nina.muller@observability.ch', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Nina Muller'),
    ('abdullah.aziz@search.sa', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Abdullah Aziz'),
    ('bianca.oliveira@realtime.br', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Bianca Oliveira'),
    ('viktor.novak@edge.cz', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Viktor Novak'),
    ('zainab.hussain@containers.iq', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Zainab Hussein'),
    ('hugo.dubois@graphql.fr', '$2a$10$rN.vUqKqSZCZZXf0nTcIKuKkV.mQzYJLQPqDZh8VQV8xZLwYx8xKO', 'Hugo Dubois')
ON CONFLICT (email) DO NOTHING;

-- Continue in next part due to size...
